version: 1.{build}

os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

test: off

clone_folder: C:\projects\ElementSyn

branches:
  only:
    - master

before_build:
  - cmd: cd C:\projects\ElementSyn
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ../

build:
  project: C:\projects\ElementSyn\build\ElementSyn.sln # path to Visual Studio solution or project
  parallel: true # enable MSBuild parallel builds
